mutation FFZ_AutoHostListUpdate($userID: ID!, $channelIDs: [ID!]!) {
  setAutohostChannels(input: {
    userID: $userID,
    channelIDs: $channelIDs
  }) {
    user {
      autohostChannels {
        nodes {
          id
          login
          displayName
          profileImageURL(width: 50)
        }
      }
    }
  }
}