query FFZ_GetClipInfo($slug: ID!) {
	clip(slug: $slug) {
		id
		curator {
			id
			login
			displayName
		}
		broadcaster {
			id
			login
			displayName
		}
		game {
			id
			displayName
		}
		title
		thumbnailURL(width: 86, height: 45)
		viewCount
	}
}