query FFZ_GetEmoteInfo($id: ID!) {
	emote(id: $id) {
		id
		artist {
			id
			login
			displayName
		}
		owner {
			id
			login
			displayName
		}
		setID
		text
		subscriptionProduct {
			id
			state
			owner {
				id
				login
				displayName
			}
		}
	}
}