query FFZ_GetVideoInfo($id: ID!) {
	video(id: $id) {
		id
		title
		previewThumbnailURL(width: 320, height: 180)
		lengthSeconds
		publishedAt
		viewCount
		game {
			id
			displayName
		}
		owner {
			id
			login
			displayName
			profileImageURL(width: 50)
		}
	}
}