query FFZ_EmoteMenu_SubStatus($first: Int, $after: Cursor, $criteria: SubscriptionBenefitCriteriaInput!) {
	currentUser {
		id
		subscriptionBenefits(first: $first, after: $after, criteria: $criteria) {
			pageInfo {
				hasNextPage
			}
			edges {
				cursor
				node {
					id
					gift {
						isGift
					}
					purchasedWithPrime
					endsAt
					renewsAt
					product {
						id
						emoteSetID
					}
				}
			}
		}
	}
}