'use strict';

// ============================================================================
// Site Support: Kick
// ============================================================================

import BaseSite from '../base';

import Elemental from 'utilities/compat/elemental';
import CSSTweaks from 'utilities/css-tweaks';
import {createElement} from 'utilities/dom';
import type {GenericModule} from 'utilities/module';

import type SettingsManager from 'src/settings';
import type TranslationManager from 'src/i18n';

import MenuButton from './menu_button';
import Chat from './chat';
import Appearance from './appearance';
import Badges from './badges';
import SevenTV from './seventv';

import MAIN_URL from './styles/kick-main.scss';

import type {SettingDefinition} from 'src/settings/types';


// Classes FrankerFaceZ's stylesheets key off. On Twitch, Twitch itself puts
// them on the root element.
const ROOT_CLASSES = ['tw-root--theme-dark', 'tw-root--hover'];

// Settings that can't do anything on Kick yet stay out of the control
// center here. They configure parts of chat FFZ doesn't render on Kick
// (Twitch badges, mod actions, deleted messages) or
// Twitch-only features (bits, GIFs, AutoMod, GraphQL). Add-on changelogs
// go too, since no add-on targets Kick yet.
// Menu locations in key form; a location hides everything under it.
const HIDDEN_SETTING_PATHS = [
	'add_ons.changelog',
	'chat.actions',
	'chat.badges.behavior',
	'chat.badges.tabs',
	'chat.bits_and_cheering',
	'chat.viewer_cards',
	'chat.behavior.deleted_messages',
	'chat.behavior.general',
	'chat.appearance.gifs',
	'chat.filtering.general.auto_mod_filters',
	'chat.filtering.block.badges',
	'chat.filtering.highlight.badges',
	'chat.filtering.highlight.users',
	'chat.tooltips.badges',
	'debugging.graph_ql'
];

// Individual settings, for sections that otherwise apply.
const HIDDEN_SETTINGS = new Set([
	'chat.fix-bad-emotes',
	'chat.emotes.allow-gigantify',
	'chat.name-format',
	'chat.font-size',
	'chat.font-family',
	'chat.timestamp-size',
	'chat.lines.emote-alignment',
	'chat.me-style'
]);


// ============================================================================
// The Site
// ============================================================================

export default class KickSite extends BaseSite {

	// Dialogs (the control center) go in our own container rather than
	// anywhere in Kick's tree.
	static DIALOG_EXCLUSIVE = '.ffz-kick-root';
	static DIALOG_MAXIMIZED = '.ffz-kick-root';
	static DIALOG_SELECTOR = '.ffz-kick-root';

	// Dependencies
	settings: SettingsManager = null as any;
	i18n: TranslationManager = null as any;
	elemental: Elemental = null as any;
	css_tweaks: CSSTweaks = null as any;
	menu_button: MenuButton = null as any;
	chat: Chat = null as any;
	appearance: Appearance = null as any;
	badges: Badges = null as any;
	seven_tv: SevenTV = null as any;

	// State
	/**
	 * Everything of ours that isn't attached to Kick's own UI (for now,
	 * the control center) renders into this container.
	 */
	container: HTMLElement | null;

	private _root_observer: MutationObserver | null;

	constructor(name?: string, parent?: GenericModule) {
		super(name, parent);

		this.inject('settings');
		this.inject('i18n');

		this.inject('elemental', Elemental);
		this.inject('css_tweaks', CSSTweaks);

		this.css_tweaks.loader = require.context(
			'./css_tweaks?css_tweaks', false, /\.s?css$/, 'lazy-once'
		);

		// Elements the layout settings hide (see appearance.ts). Kick's
		// class names are generated by Tailwind, so these lean on ids,
		// test ids and structure instead.
		this.css_tweaks.rules = {
			'sidebar-recommended': '#sidebar-wrapper section:has([data-testid^="sidebar-recommended-channel-"])',
			'gift-subs': '#channel-content button:has(svg[data-ds-icon^="Gift"])',
			'kicks-balance': 'nav a[href*="/kicks"], nav [data-testid*="kicks" i]',
			'chat-banners': '#channel-chatroom div:has(> div > #chatroom-messages) > div:first-child, #channel-chatroom div:has(> #chatroom-messages) > div.absolute.w-full',
			'chat-divider': '#chatroom-messages [data-index].ffz--kick-divider > div',
			'quick-emotes': '#chatroom-footer > div > div:has(img[src*="/emotes/"]):not(:has(#chat-input-wrapper))',
			'chat-stats': '#chatroom-footer div:has(> #chat-input-wrapper) + div > div:first-child'
		};

		this.inject('menu_button', MenuButton);
		this.inject('chat', Chat);
		this.inject('appearance', Appearance);
		this.inject('badges', Badges);
		this.inject('seven_tv', SevenTV);

		this.container = null;
		this._root_observer = null;
	}

	onEnable() {
		const html = document.documentElement;
		html.classList.add(...ROOT_CLASSES);

		// Kick is a React app and can rewrite the root element's class list
		// when it re-renders. Put ours back if that happens.
		this._root_observer = new MutationObserver(() => {
			if ( ! ROOT_CLASSES.every(cls => html.classList.contains(cls)) )
				html.classList.add(...ROOT_CLASSES);
		});
		this._root_observer.observe(html, {attributes: true, attributeFilter: ['class']});

		// kick-main.scss sizes and positions the container.
		this.container = createElement('div', {className: 'ffz-kick-root'});
		document.body.appendChild(this.container);

		document.head.appendChild(createElement('link', {
			href: MAIN_URL,
			rel: 'stylesheet',
			type: 'text/css',
			crossOrigin: 'anonymous'
		}));

		// Kick only has a dark theme. The setting has no control center
		// entry, which the definition type otherwise insists on.
		this.settings.add('theme.is-dark', {
			default: true
		} as SettingDefinition<boolean>);

		this.settings.updateContext({
			kick: true,
			ui: {
				theme: 1
			}
		});

		// Window Size
		const update_size = () => this.settings.updateContext({
			size: {
				height: window.innerHeight,
				width: window.innerWidth
			}
		});

		window.addEventListener('resize', update_size);
		update_size();
	}

	onDisable() {
		if ( this._root_observer ) {
			this._root_observer.disconnect();
			this._root_observer = null;
		}

		if ( this.container ) {
			this.container.remove();
			this.container = null;
		}
	}

	// Asked by the control center for every setting it lists.
	isSettingVisible(key: string, path: string) {
		if ( HIDDEN_SETTINGS.has(key) )
			return false;

		for(const hidden of HIDDEN_SETTING_PATHS)
			if ( path === hidden || path.startsWith(`${hidden}.`) )
				return false;

		return true;
	}

	// The site API shared modules expect. Kick's session isn't wired up yet.
	getCore() { return null; }
	getSession() { return null; }
	getUser() { return null; }
}
