'use strict';

// ============================================================================
// Menu Button
// Puts the FrankerFaceZ Control Center button in Kick's top navigation.
// ============================================================================

import Module from 'utilities/module';
import {createElement} from 'utilities/dom';


export default class MenuButton extends Module {
	constructor(...args) {
		super(...args);

		this.inject('i18n');
		this.inject('site.elemental');

		this.should_enable = true;
		this.menu_loading = false;

		// Kick's top bar, matched by the sidebar toggle it carries; its
		// class list is generated by Tailwind and nothing to depend on.
		// Watched for as long as the page lives, since Kick re-renders the
		// bar on some navigations. Its children are watched too: React
		// rebuilds the right-hand group (where our button sits) when the
		// login state resolves, which throws the button out.
		this.NavBar = this.elemental.define(
			'nav-bar', 'nav:has([data-testid="sidebar-expand"])',
			null, {childList: true, subtree: true}, 1, 0
		);
	}

	onEnable() {
		this.NavBar.on('mount', this.updateButton, this);
		this.NavBar.on('mutate', this.updateButton, this);
		this.NavBar.each(el => this.updateButton(el));

		this.on('i18n:update', this.update, this);
		this.once(':clicked', this.loadMenu, this);
	}

	onDisable() {
		this.NavBar.off('mount', this.updateButton, this);
		this.NavBar.off('mutate', this.updateButton, this);
		this.off('i18n:update', this.update, this);

		for(const el of document.querySelectorAll('.ffz-top-nav'))
			el.remove();
	}

	update() {
		this.NavBar.each(el => this.updateButton(el));
	}

	updateButton(nav) {
		// Our button goes at the start of the bar's right-hand group,
		// beside the language picker and the account controls.
		const container = nav.lastElementChild;
		if ( ! container )
			return;

		let el = nav.querySelector('.ffz-top-nav');
		if ( ! el ) {
			el = (<div class="ffz-top-nav">
				<button
					class="ffz-top-nav__button ffz-tooltip"
					onClick={e => this.handleClick(e, el)} // eslint-disable-line react/jsx-no-bind
				>
					<figure class="ffz-i-zreknarf" />
				</button>
			</div>);

			container.insertBefore(el, container.firstChild);
		}

		const btn = el.querySelector('button');
		btn.dataset.title = this.i18n.t('site.menu_button', 'FrankerFaceZ Control Center');
		btn.querySelector('figure').classList.toggle('loading', this.menu_loading);
	}

	handleClick(event, btn) {
		this.emit(':clicked', event, btn);
	}

	// Toasts are how the rest of the client tells the user about problems.
	// There's no UI for them on Kick yet, so they go to the console.
	addToast(data) {
		this.log.info('Toast:', data?.text ?? data);
	}

	addError(i18n, text) {
		this.addToast({text_i18n: i18n, text});
	}

	loadMenu(event) {
		const menu = this.resolve('main_menu');
		if ( ! menu || menu.showing )
			return;

		this.menu_loading = true;
		this.update();

		menu.enable(event).then(() => {
			this.menu_loading = false;
			this.update();

		}).catch(err => {
			this.log.error('Error enabling main menu.', err);
			this.addError(
				'site.menu_button.error',
				'There was an error loading the FFZ Control Center. Please refresh and try again.'
			);

			this.menu_loading = false;
			this.update();
			this.once(':clicked', this.loadMenu, this);
		});
	}
}
