query {
	currentUser {
		followedLiveUsers {
			nodes {
				stream {
					createdAt
				}
			}
		}
		followedHosts {
			nodes {
				profileImageURL(width: 50)
				hosting {
					stream {
						createdAt
					}
				}
			}
		}
	}
}