query {
	currentUser {
		followedLiveUsers {
			nodes {
				profileImageURL(width: 50)
				stream {
					createdAt
				}
			}
		}
		followedHosts {
			nodes {
				profileImageURL(width: 50)
				hosting {
					profileImageURL(width: 50)
					stream {
						createdAt
						type
					}
				}
			}
		}
	}
}