query FollowedChannels_RENAME2 {
	currentUser {
		follows {
			edges {
				node {
					stream {
						createdAt
						type
					}
				}
			}
		}
		followedLiveUsers {
			nodes {
				stream {
					createdAt
				}
			}
		}
	}
}