query {
	directory {
		... on Community {
			streams {
				edges {
					node {
						createdAt
						type
					}
				}
			}
		}
		... on Game {
			streams {
				edges {
					node {
						createdAt
						type
					}
				}
			}
		}
	}
}