mutation($bannedUserLogin: String!, $channelID: ID!, $expiresIn: String!) {
    banUserFromChatRoom(input: {
        bannedUserLogin: $login,
        channelID: $channelID,
        expiresIn: $expiresIn
    }) {
        ban {
            isPermanent
        }
    }
}