query FFZ_ViewerCard($targetLogin: String!, $channelID: ID!) {
    targetUser: user(login: $targetLogin) {
        id
        login
        displayName
        bannerImageURL
        profileImageURL(width: 70)
        createdAt
        profileViewCount
        followers {
            totalCount
        }
        ...friendButtonFragment
    }
    channelUser: user(id: $channelID) {
        id
        login
        displayName
        subscriptionProducts {
            id
            price
            url
            emoteSetID
            emotes {
                id
            }
        }
        self {
            isModerator
        }
    }
    currentUser {
        id
        login
        roles {
            isSiteAdmin
            isStaff
            isGlobalMod
        }
    }
}

fragment friendButtonFragment on User {
    id
    self {
        friendship {
            __typename
        }
    }
}