mutation($bannedUserLogin: String!, $channelID: ID!) {
    unbanUserFromChatRoom(input: {
        bannedUserLogin: $login,
        channelID: $channelID
    }) {
        ban {
            isPermanent
        }
    }
}
