name: Build Main Client

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Uses Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .bun-version

    - name: Install Dependencies
      run: bun install --frozen-lockfile

    - name: Run Tests
      run: bun run test

    - name: Build the Client
      run: bun run build

    - name: Create Archive
      id: artifact-upload-setp
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: |
          dist

    - name: Deploy (Clean)
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: $HOME/clean-client.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy (Copy)
      uses: appleboy/scp-action@v0.1.7
      with:
        source: dist
        target: client
        strip_components: 1
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy (Execute)
      uses: garygrossgarten/github-action-ssh@release
      with:
        command:  $HOME/update-client.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
